Add Support for Multiple Configurable Sidekiq Processes
getkuby/kuby-sidekiq pull request #2
Opened 2023-03-14 22:16 UTC by zhall0624

This PR adds support for having multiple Sidekiq deployments with their own configured Sidekiq process. 

Usage

Works with the old interface:

```ruby
require 'kuby/sidekiq'
Kuby.define(:production) do
  kubernetes do
    add_plugin(:sidekiq) do
      replicas 2  # run two workers
    end
  end
end
```

This creates a Sidekiq deployment that is named `app-name-sidekiq-worker-default` with two replicas. 

To specify a more complex Sidekiq configuration:

```ruby
require 'kuby/sidekiq'
Kuby.define(:production) do
  kubernetes do
    add_plugin(:sidekiq) do
      replicas 2  # sets the default number of replicas for each process
      process('default') # sidekiq uses sidekiq.yml by default and has 2 replicas
      process('slow_process') do
        options ['-C', 'config/slow_sidekiq.yml']
        replicas 4 # override default number of replicas
      end
      process('queue_processor') do
        options ['-q', 'critical', '-q', 'less_critical']
      end
    end
  end
end
```

To accomplish this I've introduced a `SidekiqProcess` class that creates a deployment for each `process` in the kuby file. By default if no processes are defined then a default `SidekiqProcess` is created using the top level replicas value. 

I'm open to changing any naming here. I've tried to stick with the Sidekiq best practices for naming but I'm aware that some of this naming could be confusing with the `Process` module.

2023-03-23 19:52 UTC, zhall0624 commented
@camertron

2023-03-24 17:36 UTC, camertron requested changes
Awesome, thanks @zhall0624!

2023-03-24 17:36 UTC, camertron commented on lib/kuby/sidekiq/plugin.rb
> +      attr_accessor :processes
```suggestion
      def processes
        @processes ||= []
      end
```

2023-03-24 17:36 UTC, camertron commented on lib/kuby/sidekiq/plugin.rb
> +        end
```suggestion
        if processes.empty?
          processes << SidekiqProcess.new(plugin: self, default_replicas: replicas)
        end
```

2023-03-24 17:36 UTC, camertron commented on lib/kuby/sidekiq/plugin.rb
> +        self.processes ||= []
```suggestion
```

2023-03-24 17:36 UTC, camertron commented on lib/kuby/sidekiq/plugin.rb
> +        process = SidekiqProcess.new(name: name, plugin: self, default_replicas: replicas)
```suggestion
        SidekiqProcess.new(name: name, plugin: self, default_replicas: replicas).tap do |process|
          process.instance_eval(&block) if block
          processes << process
        end
```

2023-03-29 05:23 UTC, camertron requested changes
Apologies 😬 Just one more super small thing then I promise I'll merge and release 🙇

2023-03-29 05:23 UTC, camertron commented on lib/kuby/sidekiq/sidekiq_process.rb
> +    # This class creates a deployment for a Sikekiq Process. A process is a single instance
```suggestion
    # This class creates a deployment for a Sidekiq Process. A process is a single instance
```

2023-03-31 01:56 UTC, zhall0624 commented on lib/kuby/sidekiq/sidekiq_process.rb
> +    # This class creates a deployment for a Sikekiq Process. A process is a single instance
woops, updated

2023-03-31 05:44 UTC, camertron approved these changes

2023-03-31 05:44 UTC, merged

2023-03-31 05:47 UTC, camertron commented
Published in v0.5.0.